### ISSUE TITLE
Support for "default" state isn't immediately intuitive

### ISSUE THREAD

**Issue by eeik** [dxinteractive/AnalogMultiButton#4]
While reviewing the source code for this library as I ran into some issues with button states, I realized that there doesn't seem to be an obvious "base case" handling for  the "no buttons are pressed" scenario. I've worked around this by adding the base case voltage as a separate button within the button value array.

Within the constructor, the following comments are made which were helpful to illuminate why reading values between 0 and "some number smaller than my initial button" rendered an active button press.

```
// determine value boundaries, so we can easily determine which button has the closest value to the current analogRead()
// for example if values were {100, 200, 300}, then we want any value from 0-149 to trigger button 1, 150-245 to trigger button 2 etc...
```

Documentation could be tweaked to include a mention of how best to support a "no buttons pressed" base case. Perhaps something such as ==> "you should be sure to include your base case voltage reading as one of your valid button states and work around this state in your code. This makes the number of buttons you define within your code +1 from your actual button state counts.".

Loving the library by the way! Thank you!! 👍

**Comment by dxinteractive** [comment]
Hi, thanks for posting this, yes I could make this clearer.

There might be exceptions, but I would think you shouldn't have to define a "no buttons" base state, because if you following the wiring diagram then the base reading should be the same as V+, e.g. 1023. The library counts something as "no buttons pressed" when the reading is closer to 1023 than it is to your highest button reading. What was your "no buttons pressed" reading?

**Comment by faljse** [comment]
My default readAnalog is also 0, so i have to use a dummy button as well.
There is a fixed pull-down in my hardware (Controllino).

Why not make the library work both ways (or document this workaround)?
